### ISSUE TITLE
再生者以外にデバイス指定ボタンを押させない

### ISSUE THREAD

**Issue by dora1998** [camphor-/relaym-client#121]
再生者以外が後からデバイスを指定し直すことはAPI仕様上できないので、ボタンを無効化するなどする必要がある

**Comment by dora1998** [comment]
@p1ass これってv3ではどうなってる？

**Comment by p1ass** [comment]
現状では デバイスを取得するAPIは Spotifyにログインしている人しか叩けない(今まで通りの仕様)
だから無効化する必要がある。

ただUXを考えて、「セッションの作成者以外がボタンを押したらセッションの作成者の端末を表示できる」というふうに変えることもできる

**Comment by p1ass** [comment]
@dora1998 これ挙動どうしようっか？
ボタンを押させないくらいなら、作成者のデバイスを表示してしまっても良いかなと思ったんだけど

**Comment by dora1998** [comment]
そうしませう！
