### ISSUE TITLE
active device not found 対策

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-client#195]
## 現象

こちらのまとめを参照

https://github.com/camphor-/relaym-server/blob/master/docs/sotify_api_problem.md

## 対策

@dora1998 サーバーサイドだけでは限界があるので、クライアント側と合わせて対策を考えたい〜

エラったら、 https://open.spotify.com のリンクを踏んでもらって、アプリを起動してもらうことってできそうかな？
(他にも良い方法があれば教えてほしい)

**Comment by p1ass** [comment]
duplicate #193

**Comment by p1ass** [comment]
全然duplicateじゃなかったのでrepone

**Comment by dora1998** [comment]
手元で試した感じ、

- https://open.spotify.com/ : 🙅
- https://open.spotify.com/home : 🙆

のようなので、ドメイントップ以外の/homeや/browse/hogeとかを開く必要がありそう。
上の動作はiOS/Android両方で確認済み。

**Comment by p1ass** [comment]
なるほど

そしたらそれを開くように誘導する実装があると良さそう

**Comment by dora1998** [comment]
曲のexternalUrlをスマホで開くと、再生まで行われる。
active device not foundがきたら、**次再生予定の曲** のリンクを開かせると良さそう

**Comment by p1ass** [comment]
↑の挙動はセッション作成者の端末でのみ行える
普通の参加者のデバイスでやっても意味はない

**Comment by p1ass** [comment]
これexternal_urlクリックすれば最初の曲は再生されるけど、2曲目以降のキューがSpotify側に積まれてないから、このままだとまずい、、、

サーバー側で上手くキューをセットできないか調べるわ

**Comment by sanposhiho** [comment]
上で議論されてる解決策ってexternal_urlをクライアントで開くことでサーバー側でplayをSpotifyAPIでたたかなくても再生されるってことであってますか？
（叩かなくてもというか[特定の条件](https://github.com/camphor-/relaym-server/blob/master/docs/sotify_api_problem.md)でplayをSpotifyAPIで叩くとactive device not foundが出ちゃうって話ですよね）

> これexternal_urlクリックすれば最初の曲は再生されるけど、2曲目以降のキューがSpotify側に積まれてないから、このままだとまずい、、、

このactive device not foundの時ってサーバー側のtimerとかもスタートしてない感じです…よね？
サーバー側も合わせて解決するとすると`active device not found`のエラーの時は

(サーバー)

- Playを叩く（sessionUsecase.stopToPlay内のPlayWithTracks）
- active device not foundが帰る（本来だとここでエラーハンドル）
- active device not foundのときはいったん無視してその後の正常系の処理を続行
- relaym-clientに`active device not found`だったよってことを何かしらで伝える

(フロント)

- `active device not found`が帰ってきたのでexternal_urlを開く（=再生される）

みたいな動作の流れになるんですかね？（正しく上で議論されてる解決策を認識できてなかったらごめんなさい）

**Comment by p1ass** [comment]
issueの途中で口頭の議論が挟まっていてわかりづらくなってるんだけど、最後にかかれている流れを想定してました！

**Comment by sanposhiho** [comment]
なるほど了解納得です！
だったら[このPR](https://github.com/camphor-/relaym-server/pull/126)は関係なさそうなのでOKだと思います！

**Comment by sanposhiho** [comment]
あー関係なくは無いかもしれない
skipAllTracksでダミー曲の再生時点で`active device not found`が帰ってくるので、
>active device not foundのときはここでエラーで返さずいったん無視してその後の正常系の処理を続行

の「ここ」のタイミングが変わる感じですかね

**Comment by p1ass** [comment]
active device not found対策時のシーケンス図書いときました！
(修正案がある場合はシーケンス図のUMLをesaにコピって編集してくれると、良い感じに画像を生成してくれます)

<img width="1060" alt="スクリーンショット 2020-07-04 23 17 19" src="https://user-images.githubusercontent.com/30015728/86514339-c0396400-be4c-11ea-938f-35e8554be50c.png">

<details>
<summary>UMLのコード</summary>

```uml
title STOP → PLAY時のシーケンス
autonumber 1001
ブラウザ -> Relaym: 再生ボタンをクリック POST /playback
activate Relaym
    Relaym -> SpotifyAPI: 不要なキューのスキップを試みる
    alt active deviceが存在するとき
        SpotifyAPI --> Relaym: 曲をスキップ
        Relaym -> SpotifyAPI:  今から再生する曲を再生
        SpotifyAPI --> Relaym: 成功レスポンス
        Relaym -> SpotifyAPI:  キューに曲を追加
        SpotifyAPI --> Relaym: 成功レスポンス
           Relaym -> Relaym: タイマーなどの再生開始時の処理を行う
        Relaym --> ブラウザ: 成功レスポンス
    else active device not foundのとき
        autonumber 1100
        SpotifyAPI --> Relaym: active device not found エラー
        Relaym --> ブラウザ: active device not found エラー
        ブラウザ -> Spotifyアプリ: external_urlへリダイレクト
        Spotifyアプリ -> Spotifyアプリ: タップした曲の再生が開始される
        Relaym -> Relaym: タイマーなどの再生開始時の処理を行う
        return: <既にAPIレスポンスは返しているので何も起こらない>
    end
```

</details>

**Comment by p1ass** [comment]
> ↑の挙動はセッション作成者の端末でのみ行える
> 普通の参加者のデバイスでやっても意味はない
https://github.com/camphor-/relaym-client/issues/195#issuecomment-650902147

あ、完全にセッション作成者以外の端末で再生ボタン押されたときのこと考え忘れてた、、、
作成者以外の端末でactive device not foundのシーケンス実行しても無意味じゃん、、、

**Comment by p1ass** [comment]
実装し終わってから気づいた😇

**Comment by sanposhiho** [comment]
[アーカイブの時](https://github.com/camphor-/relaym-server/issues/122#issuecomment-650914988)みたいにセッション作成者以外だったら「セッションを再開したい場合は作成者に連絡をとってください」的なのを出すのはどうですか？

**Comment by p1ass** [comment]
まぁそうするしかないかー
再生処理を続行するのは作成者のときのみって感じかな？

**Comment by sanposhiho** [comment]
んーですかね…（それ以外にいい感じの方法思いつかない…

**Comment by p1ass** [comment]
その方針で行くか〜と思ったけど、middlewareのタイミングで作成者のトークンを流し込んでるせいで、今のままユースケース内でセッション作成者かどうか判定する方法ないのか、、、

contextにセッション作成者かどうかの情報突っ込むか...?

**Comment by p1ass** [comment]
そうしよう

**Comment by p1ass** [comment]
色々とさんぽし君と議論してたんだけど、STOP→PLAY(1曲目の再生時)にactive device not foundになったときの対応が難しい。

PLAY時には
1. Spotifyの曲を全部スキップ
2. 再生
3. 次の曲をEnqueueする

という処理をしているのだが、すべてactive deviceである必要がある。

そのため、active device not foundだったら、クライアント側でSpotifyアプリに遷移した後、1と3を行う必要がある。(2は遷移したら自動で再生が開始される)

しかし、2で再生が始まってる状態で、1のスキップを行うと、再生が途中で切れてしまう問題が起きてしまう。
スキップをしないと、変なキューが残ったままになり、INTERRUPTが発火されてしまう。

色々考えた結果、一番シンプルかつすべての問題を解決できるのは、「active device not found」だったら、クライアント側で、手動/自走でアプリを開いて再生ボタンを 挙動にするのがベストな気がしてきた

<img width="963" alt="スクリーンショット 2020-07-23 14 05 54" src="https://user-images.githubusercontent.com/30015728/88253680-ad98a900-cced-11ea-9c7a-4f5f6cf385a8.png">

**Comment by p1ass** [comment]
これ終わったのでclose
