### ISSUE TITLE
スリープから復帰したときに画面に表示されている情報が古い

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-client#217]
## 現象

- 画面をスリープするとプログレスバーが止まるので、再生時間がおかしい
- WebScoketのコネクションが切れてしまうので、セッションを取得するAPIが叩かれない
  - 現在されている曲が異なったり、キューに新しい曲が追加されていなかったりする

**Comment by dora1998** [comment]
Androidでは、

- 他アプリ遷移後戻る: 問題なし
- 一定時間スリープ: 途中のタイマーが飛んで、楽曲の進捗状況が遅れて表示される？

みたいな挙動になった（もうちょい調べる）

**Comment by dora1998** [comment]
freeze, resumeはChromeのみ対応なので、visibilitychangeで中断と再開の処理を書くのが良さそう

https://developers.google.com/web/updates/2018/07/page-lifecycle-api
https://qiita.com/d2cd-kimura/items/b51ef73528fa66a35a9d
https://developer.mozilla.org/ja/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API

**Comment by dora1998** [comment]
visibilitychangeで軽く検証用コード書いてみたけど、ちゃんとスリープや他アプリ移動で動いていい感じ
https://cdpn.io/dora1998/debug/jOWpYEb/NQAzYBmanzQr

**Comment by p1ass** [comment]
へ〜便利

**Comment by dora1998** [comment]
ただ、これ「スリープ時と復帰時」ではなく「復帰時に2回」呼ばれる場合があってめんどくせえ…
