### ISSUE TITLE
セッション作成時に名前を入力する必要があるのか問題

### ISSUE THREAD

**Issue by p1ass** [camphor-/relaym-client#221]
## 辛い点

- セッションの名前を入れるのがめんどい

## 論点

- そもそも名前って必要なの？
  - セッションの検索があるわけではないので、名前を使う用途はない

## 対応案

- セッションの名前という概念をなくす
- サーバで適当な名前を生成してしまう

@dora1998  @sanposhiho @atrn0 どうしたら良いと思います？

**Comment by dora1998** [comment]
@p1ass 「シェア時の文言にタイトル活かしたら良さそう」

**Comment by dora1998** [comment]
#301 で活用するので一旦close
