### ISSUE TITLE
Restricted deviceを選択リストから外す

### ISSUE THREAD

**Issue by dora1998** [camphor-/relaym-client#234]
## What

デバイス一覧取得時に、Restricted deviceを選択リストから外す。

## Why

Restricted device（具体的には、Amazon Echo等）は、「次に再生」などRelaymに必要な機能が一部使えない。
cf) https://github.com/camphor-/relaym-server/issues/123

**Comment by p1ass** [comment]
バグってると思ったが、これ既にRestricted Device弾いてる説がある、、、

https://github.com/camphor-/relaym-client/blob/develop/store/pages/sessions/detail.ts#L34-L36

https://github.com/camphor-/relaym-client/blob/develop/components/organisms/DeviceSelectDialog.vue#L33

**Comment by p1ass** [comment]
↑すでに弾いているように見えるんだけど解決は出来てない、、、

**Comment by p1ass** [comment]
```
{"time":"2020-06-29T07:59:16.333685272Z","level":"ERROR","prefix":"application","file":"session.go","line":"138","error":"playORResume sessionID=e2990b0d-1a90-4997-a8c4-3855b5a3c250: start to play: call add queue api trackURI=spotify:track:2iGt8kJKM7cUF9TEr50XGF: spotify api: add queue: Restricted device: non-premium user","message":"failed to change playback"}
```

改めてログみたけど、`non-premium user` になってね？？

**Comment by dora1998** [comment]
なぜだろう…、Spotifyのアカウント複数持ってるとかそういうことはないはず

**Comment by p1ass** [comment]
もう一度再現させてログを吐かせないと何も分からねえな、、、

**Comment by dora1998** [comment]
どうしようもなさそうなのでclose
