### ISSUE TITLE
セッションページでタイトルを活用する

### ISSUE THREAD

**Issue by dora1998** [camphor-/relaym-client#301]
- ページの<title>にセッション名を入れる
- シェア時にセッション名を含める

あたりをすると良さそう

**Comment by dora1998** [comment]
これ現状

```
Relaymで一緒にセッションを楽しもう！ https://relaym.camph.net/~~~
```

ってなっているけど、どこにセッション名含めよう？


```
[セッションのタイトル] | Relaym - Spotifyの楽曲を1つのスピーカーで楽しめるWebアプリ https://relaym.camph.net/~~~
```

ページタイトルと揃えてにするとか？

**Comment by p1ass** [comment]
ん〜それだと招待してる感じがしないし、
`〇〇さんがセッション「{セッションのタイトル}」に招待しています。Relaymで一緒にセッションを楽しもう！ https://relaym.camph.net/~~~`
とかのほうが良さそう

**Comment by dora1998** [comment]
それ良さそう。ただ、 `〇〇さん` についてはセッション作成者以外も招待できるので無理そう…？

**Comment by p1ass** [comment]
確かに
なくても良さそう

**Comment by dora1998** [comment]
de54ba9 で変更したのでclose
