### ISSUE TITLE
ランディングページの内容を詰める

### ISSUE THREAD

**Issue by marty958** [camphor-/relaym-client#88]
# ランディングページの内容をリスト化する
## 書くべきこと
- アプリの概要
　- 何ができるか
　- 読み方
- アプリの使い方
　- ユースケース（ex. 友達と一緒に..etc）

## 書いてあると良さそうなもの
- 製作者名
（必要なことがあれば追記してください）

**Comment by p1ass** [comment]
これをそろそろ作りたい

**Comment by p1ass** [comment]
![image](https://user-images.githubusercontent.com/30015728/87850458-59777880-c92b-11ea-9d5a-7fb4f754dfc9.jpeg)

![image](https://user-images.githubusercontent.com/30015728/87850461-5c726900-c92b-11ea-83ef-1ac00b08ac62.jpeg)

**Comment by dora1998** [comment]
XDでざっとデザインに起こした！！！
![Home](https://user-images.githubusercontent.com/31735614/88156610-9f428280-cc44-11ea-9f4d-26d91d607f70.png)

**Comment by marty958** [comment]
イラスト原案
どうでしょうか？
![image](https://user-images.githubusercontent.com/25263051/88277508-d46dd400-cd1b-11ea-8962-661ca2dfbe9b.png)

**Comment by dora1998** [comment]
かわいくて良いと思います！
ただ、サイズが96px x 96pxなので、2つ目3つ目あたりは簡略化してシンプルにした方が良さそうです

**Comment by p1ass** [comment]
とても可愛いです！

**Comment by marty958** [comment]
イラストって丸型に描いたらいいですか？

**Comment by dora1998** [comment]
@marty958 丸型の背景はCSSで描画してるので必要ないです
96x96ぴったり使って描いていただけると！

今のトップページに仮で置いている画像がこんな感じになっています
![image](https://user-images.githubusercontent.com/31735614/88481854-c7114d80-cf98-11ea-96bc-717c69a63ab5.png)

**Comment by p1ass** [comment]
@marty958 実装はほとんど終わったので、画像を差し替えたら宣伝しようと思うのですが、いつ頃にできそうですか？（急かす意図は全くなくて、自分のペースでやってもらって大丈夫です！）

**Comment by marty958** [comment]
一枚目
![image](https://user-images.githubusercontent.com/25263051/89095735-aec38780-d40b-11ea-9bec-e40159378a6f.png)

**Comment by marty958** [comment]
2枚目
https://camphor.slack.com/archives/CL26RAMK5/p1596263290059300
![image](https://user-images.githubusercontent.com/25263051/89096574-89864780-d412-11ea-829a-7a4b52cc5079.png)

**Comment by marty958** [comment]
3枚目
https://camphor.slack.com/archives/CL26RAMK5/p1596278201089800
![image](https://user-images.githubusercontent.com/25263051/89099982-5ea9ec80-d42e-11ea-8245-126e20b5ce93.png)

**Comment by marty958** [comment]
https://camphor.slack.com/archives/CL26RAMK5/p1596278201089800

**Comment by marty958** [comment]
![image](https://user-images.githubusercontent.com/25263051/89102507-edc1ff00-d444-11ea-8f02-1563b37f7dd8.png)
